# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5deef3f58dfe65e8ba157ec2969bc43dcb8bf84b23412bf0e99194eac82350133d941297631d553210913becf88be12b82fe66cf14e35edebe2b9560c0196081

test:
  secret_key_base: 76db70ab2799528946d852f1f759856e13b94c07b7ea2b91921e3b8b7abdcbc9d5f736d17dc5ab24ae922d795578c4c45fb542e84838770a0b9859dab64277ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
